GET http://localhost:3000/api/v1/workspace/list
content-type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjllY2VhNTYwLThkMmItNDE4NC04OWVmLTY2NWY5ZWZjMjg1YSIsIm5hbWUiOiJidWJhbyIsImVtYWlsIjoiZXhhbXBsZUB0ZXN0LmNvbSIsImNyZWF0ZV90aW1lIjoiMjAyMi0wMS0yM1QwODoyNzoyMi4wMDBaIiwiaWF0IjoxNjQzMTM0MDE1LCJleHAiOjE2NDMxNDEyMTV9.tnREjtIfXE2VI7sNd2-Wr7RydjXRqg2EjMMRvQJ4zOo
