PATCH http://localhost:3000/api/v1/users/info
content-type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjllY2VhNTYwLThkMmItNDE4NC04OWVmLTY2NWY5ZWZjMjg1YSIsIm5hbWUiOiLkuIDlv7UiLCJlbWFpbCI6ImV4YW1wbGVAdGVzdC5jb20iLCJjcmVhdGVfdGltZSI6IjIwMjItMDEtMjNUMDg6Mjc6MjIuMDAwWiIsImlhdCI6MTY0MzA3ODEzNSwiZXhwIjoxNjQzMDg1MzM1fQ.zgPsD75b0lPrQJfA4uHNZh4b9rScfcdoduFh4OddM90

{
	"name": "bubao"
}