DELETE http://localhost:3000/api/v1/auth
content-type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjllY2VhNTYwLThkMmItNDE4NC04OWVmLTY2NWY5ZWZjMjg1YSIsIm5hbWUiOiLkuIDlv7UiLCJlbWFpbCI6ImV4YW1wbGVAdGVzdC5jb20iLCJjcmVhdGVfdGltZSI6IjIwMjItMDEtMjNUMDg6Mjc6MjIuMDAwWiIsImlhdCI6MTY0MzAzODg3NywiZXhwIjoxNjQzMDQ2MDc3fQ.IhCbQvHDSsDGsBRBZN-FdlEkEtjtWagxduBhKC7BmrY
